Lesson 6 hw
NikitaPlehov/Lesson_6 pull request #1
Opened 2021-12-08 17:47 UTC by NikitaPlehov

2021-12-13 11:59 UTC, wildpioneer requested changes

2021-12-13 11:59 UTC, wildpioneer commented on src/test/java/tests/HW.java
> +        // premisesDropDown.selectByIndex(1);
Перед отправкой на проверку лучше почистить код и удалить все лишние комментарии

2021-12-13 11:59 UTC, wildpioneer commented on src/test/java/tests/HW.java
> +
Ты хорошо разделяешь код на логические блоки, для чего здесь пустая строка?

2021-12-13 11:59 UTC, wildpioneer commented on src/test/java/tests/HW.java
> +        Thread.sleep(10000);
С какой целью здесь ожидание 10 секунд?

2021-12-13 11:59 UTC, wildpioneer commented on src/test/java/tests/HW.java
> +        Thread.sleep(25000);
Старайся придерживаться единообразия в форматировании

2021-12-13 11:59 UTC, wildpioneer commented on src/test/java/tests/HW.java
> +
Большое количество пустых строк наводит на мысль, что тут что-то не закончено и ты забыл что-то

2021-12-20 05:30 UTC, NikitaPlehov commented
Все доделал.

2022-01-17 13:19 UTC, closed without merging