Lesson 7
NikitaPlehov/Lesson_6 pull request #3
Opened 2021-12-14 08:31 UTC by NikitaPlehov

Домашка HM2.

2021-12-19 18:51 UTC, wildpioneer requested changes

2021-12-19 18:51 UTC, wildpioneer commented on src/test/java/tests/HM2.java
> +        private static String path3_2 = "//div//ul//a";   //аналог только проще.
Если это аналог предыдущей - тогда он должен быть "//div/ul//a"; - один слеш по середине

2021-12-20 05:24 UTC, NikitaPlehov commented on src/test/java/tests/HM2.java
> +        private static String path3_2 = "//div//ul//a";   //аналог только проще.
Переделал!

2021-12-20 05:30 UTC, NikitaPlehov commented
Все доделал.

2022-01-17 13:19 UTC, closed without merging