Page object simple hm
NikitaPlehov/Lesson_6 pull request #4
Opened 2021-12-16 11:31 UTC by NikitaPlehov

Домашку сделал!
По-моему даже правильно))
Первый тест - вход на аккаунт и выбор проекта через xpath, как вы просили.
Второй тест - вход, добавление проекта, ввод информации, сохранение и проверка.

2021-12-19 18:52 UTC, wildpioneer commented
PR надо делать в PageObject_Simple

2021-12-19 18:59 UTC, wildpioneer requested changes

2021-12-19 18:59 UTC, wildpioneer commented on src/test/java/pages/AddProjectPage.java
> +        return driver.findElement(check_Selector);
Форматирование

2021-12-19 18:59 UTC, wildpioneer commented on src/test/java/pages/DashboadPage.java
> +    private By projects_Selector = By.xpath("(//div[@class='table summary summary-auto']/following::div/*[@class = 'row project flex-projects-row'])[15]//a[@style='padding-left: 25px']");
Если это просто для примера - то пойдет, а иначе - слишком сложно

2021-12-19 18:59 UTC, wildpioneer commented on src/test/java/tests/SmokeTest.java
> +    @Test
Пустая строка

2021-12-20 05:29 UTC, NikitaPlehov commented on src/test/java/pages/AddProjectPage.java
> +        return driver.findElement(check_Selector);
Переделал!

2021-12-20 05:29 UTC, NikitaPlehov commented on src/test/java/pages/DashboadPage.java
> +    private By projects_Selector = By.xpath("(//div[@class='table summary summary-auto']/following::div/*[@class = 'row project flex-projects-row'])[15]//a[@style='padding-left: 25px']");
Как пример)

2021-12-20 05:29 UTC, NikitaPlehov commented on src/test/java/tests/SmokeTest.java
> +    @Test
Переделал!

2021-12-20 05:30 UTC, NikitaPlehov commented
Все переделал.

2021-12-20 05:33 UTC, NikitaPlehov commented
Готово!

2022-01-17 13:20 UTC, closed without merging